---
stages:
  - test

workflow:
  rules:
    # Run if this is a merge request
    - if: $CI_MERGE_REQUEST_ID

workstation-testing:
  stage: test
  variables:
    CINC_REF: $CI_COMMIT_REF_NAME
  trigger:
    project: cinc-project/distribution/workstation
    strategy: depend
