source "https://rubygems.org"

gem "omnibus", github: ENV.fetch("OMNIBUS_GITHUB_REPO", "chef/omnibus"), branch: ENV.fetch("OMNIBUS_GITHUB_BRANCH", "main")
gem "omnibus-software", git: ENV.fetch("OMNIBUS_SOFTWARE_GIT_REPO", "https://gitlab.com/cinc-project/upstream/omnibus-software.git"), branch: ENV.fetch("OMNIBUS_SOFTWARE_GIT_BRANCH", "stable/cinc")

gem "artifactory"

gem "pedump"

# This development group is installed by default when you run `bundle install`,
# but if you are using Omnibus in a CI-based infrastructure, you do not need
# the Test Kitchen-based build lab. You can skip these unnecessary dependencies
# by running bundle config set --local without dep_selector && bundle install to speed up build times.
group :development do
  # Use Berkshelf for resolving cookbook dependencies
  gem "berkshelf", ">= 8.0"

  # Use Test Kitchen with Vagrant for converging the build environment
  gem "test-kitchen", ">= 2"
  gem "kitchen-vagrant"
  gem "winrm-elevated"
end
