#!/bin/sh
#
# Perform necessary steps to uninstall
# Chef Workstation.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

is_darwin()
{
  uname -a | grep "^Darwin" 2>&1 >/dev/null
}

if is_darwin; then
  echo "This uninstaller will remove Cinc Workstation."
  sudo /bin/sh -s <<'EOF'
echo "Uninstalling Cinc Workstation..."
echo "  -> Removing files..."
sudo rm -rf '/opt/chef-workstation'
echo "  -> Removing binary links in /usr/local/bin..."
sudo find /usr/local/bin -lname '/opt/chef-workstation/*' -delete
echo "  -> Forgetting com.getchef.pkg.chef-workstation package..."
sudo pkgutil --forget com.getchef.pkg.chef-workstation > /dev/null 2>&1;
echo "Cinc Workstation Uninstalled."
EOF
fi
